### ISSUE TITLE
Website missing

### ISSUE THREAD

**Issue by lurch** [davidferguson/pibakery-blocks#1]
What's happened to http://pibakery.tk ?

**Comment by davidferguson** [comment]
What happened is I bought [pibakery.org](http://pibakery.org), and updated my virtualhost config for that, forgetting to also include [pibakery.tk](http://pibakery.tk) in there. So [pibakery.tk](http://pibakery.tk) was redirected to the Apache default page.
This has now been fixed. Thank!

**Comment by carlosperate** [comment]
The .org website still prints `http://pibakery.tk` to the bottom of the page. Also, it would help people to discover the new domain if the .tk page did a "normal" redirect to the .org website instead of having both domains serving the same content.
Btw, any expected date for the pibakery release?
