### ISSUE TITLE
New block suggestion: install ssh public key

### ISSUE THREAD

**Issue by dkirkby** [davidferguson/pibakery-blocks#14]
This would be a block under "Settings" where you paste in a public ssh key and it will add it to .ssh/authorized_keys, creating .ssh and authorized_keys with the necessary permissions, if necessary.

**Comment by dan3008** [comment]
sounds like it would be a really simple, and really useful block. Once I've finished the Alias block i'm working on, I'll move onto that if someone else hasnt already done it.
