### ISSUE TITLE
New block suggestion: update and upgrade OS packages

### ISSUE THREAD

**Issue by dkirkby** [davidferguson/pibakery-blocks#15]
This can already be achieved using a pair of "Run Command" blocks, but it might be worth creating a dedicated block to encourage best practices and save people the trouble of looking up the [relevant commands](https://www.raspberrypi.org/documentation/raspbian/updating.md) and modifying them to [run non-interactively](http://serverfault.com/questions/227190/how-do-i-ask-apt-get-to-skip-any-interactive-post-install-configuration-steps):
```
sudo DEBIAN_FRONTEND=noninteractive apt-get -y update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
```

**Comment by AntoCuc** [comment]
Further to the above it would allow users to further abstract the Raspbian-specific commands. In the event in which pibakery, in the future, may support more than on RPi OS.

![image](https://cloud.githubusercontent.com/assets/682320/18387006/ebbc2fec-7691-11e6-88c3-62b58b795718.png)

**Comment by davidferguson** [comment]
This has now ben committed to the repo, and will be pushed out to users in the next PiBakery block update.
