### ISSUE TITLE
PiBakery can't be installed on this disk

### ISSUE THREAD

**Issue by mrosseel** [davidferguson/pibakery-blocks#24]
Hi,

I'm getting this error while trying to install the new version of pibakery on Mac (I removed the old version). 
Any idea why I can't install on that disk?

![screen shot 2016-09-21 at 21 42 22](https://cloud.githubusercontent.com/assets/1465310/18726406/9402a062-8044-11e6-99f5-945e2c8ae4b2.png)

**Comment by davidferguson** [comment]
I've had a few reports of this now, and right now I don't know why this is happening. On my Mac (10.10) it installs fine, and I've just tested another Mac (also on 10.10) and that worked fine as well.

Could you go to Window -> Installer Log and paste the contents of all the messages here?

And could you generate a md5 checksum of the installer .pkg and paste that here as well?

**Comment by davidferguson** [comment]
I've found the bug in the installer - it turns out that the Installer formatted my install requirements, so when I typed in "5.4 GB" required, it changes it to "54 GB" required. I'm rebuilding the installer now, and will upload it as soon as I can.

Once I've uploaded it I'll add a comment here.

**Comment by davidferguson** [comment]
@mrosseel I've just uploaded the fixed installer now - if you're able to try it out and see if it works that would be very helpful.

**Comment by mrosseel** [comment]
I'll test tonight!

**Comment by mrosseel** [comment]
works perfectly now, thanks for the quick fix!
