### ISSUE TITLE
Blocks for pi-zero USB OTG?

### ISSUE THREAD

**Issue by carlosperate** [davidferguson/pibakery-blocks#3]
Are there plans to include any blocks to configure the Pi Zero OTG USB? This projects would be perfect to configure the Etherner or mass storage USB gadgets.

**Comment by davidferguson** [comment]
I sadly don't have much experience with using OTG with Pi Zero, but it's a good idea, and definitely something I can look into. However, if you've used OTG before and want to implement it yourself, you can always add it as a [custom block](http://www.pibakery.org/docs/contribute.html) if you want.

**Comment by carlosperate** [comment]
I haven't used it before and I am a bit swamped with other projects, but this would probably be one of the primary use cases for me, as configuring a headless raspberry pi zero usually requires quite a bit of reading beforehand.
Whenever you get a chance I think this would be a great addition :)

**Comment by davidferguson** [comment]
I've got them working now - just a bit more testing before I add them in.

**Comment by davidferguson** [comment]
These have now been added in to PiBakery. The OTG modes supported are g_ether, g_serial, g_mass_storage and g_midi.

For the best experience, reinstall PiBakery rather than just letting PiBakery auto-update the blocks

**Comment by carlosperate** [comment]
Great, thanks @davidferguson !

Since you've got experience with the usb gadgets now, do you know if its possible to have the composite gadget (g_multi) working on all OS (mac, win and linxu) with something like ethernet + mass storage?

**Comment by davidferguson** [comment]
I've had all the gadgets (MIDI, ethernet, mass storage and serial) working at the same time, but it doesn't work on Windows (the drivers don't exist yet). I'll have another look at ethernet + mass storage, but I have a feeling that Windows won't have the drivers for that either.
