### ISSUE TITLE
Allow installation of multiple packages

### ISSUE THREAD

**Issue by tenten8401** [davidferguson/pibakery-blocks#56]
Can you remove the `"`'s around the package names by default? When I want to install a load of packages, I shouldn't have to put them all separately. I run into this error, which is happening because of the quotes:
`E: Unable to locate package nginx php7.0 php7.0-curl php7.0-gd php7.0-fpm php7.0-cli php7.0-opcache php7.0-mbstring php7.0-xml php7.0-zip php7.0-mysql`

Would love to see this changed as it cleans things up a lot.

![image](https://cloud.githubusercontent.com/assets/6174343/20642941/5f5b2346-b3ea-11e6-906d-0358084bf1ec.png)

**Comment by Sunderfield** [comment]
Duplicate of #40

**Comment by tenten8401** [comment]
Apologies.
