### ISSUE TITLE
newcronjob block failing to create job correctly

### ISSUE THREAD

**Issue by IronBeard** [davidferguson/pibakery-blocks#65]
I have been attempting to use the newcronjob block in my Pi builds. However it has not been creating the job correctly, if any of the first 5 fields are left as default then instead of passing the default (*) it passes the directory listing.

Example:
`/boot/PiBakery/blocks/newcronjob/newcronjob.sh 0 0 "*" "*" "*" '/home/pi/bginfo Nemesis "NAS" 0' pi >>/boot/PiBakery/firstboot.log 2>&1 || true`

`su - pi -c (crontab -l ; echo 0 0 createjob.sh newcronjob.json newcronjob.sh createjob.sh newcronjob.json newcronjob.sh createjob.sh newcronjob.json newcronjob.sh /home/pi/bginfo Nemesis "NAS" 0) | crontab -`

This looks to be because the command line is expanding the * out instead of passing the * in to the command.

**Comment by IronBeard** [comment]
This is definately fixed by the code submitted by stevethomas in pull request $50
> #50 opened on Nov 14 2016 by stevethomas

**Comment by davidferguson** [comment]
Apologies for the delay, this fix is now in the repo and will be pushed out to PiBakery shortly.
