### ISSUE TITLE
sethostname block not really complete

### ISSUE THREAD

**Issue by peebles** [davidferguson/pibakery-blocks#74]
At least for the RPi3, the current "sethostname" block does not change the broadcasted hostname.  With the current block, after changing the hostname, you must still connect via "ssh pi@raspberrypi.local".  The sethostname.sh script should look like this:

```bash
#!/bin/bash

raspi-config nonint do_hostname "$1"
hostname -b "$1"
systemctl restart avahi-daemon
```

Then the broadcasted hostname is correct, no reboot needed.

**Comment by davidferguson** [comment]
Apologies for the delay in adding this fix in, it's now in the repo and will be pushed out to PiBakery shortly.
