### ISSUE TITLE
not able to write image -5

### ISSUE THREAD

**Issue by mrosseel** [davidferguson/pibakery-blocks#9]
![screen shot 2016-09-07 at 19 27 26](https://cloud.githubusercontent.com/assets/1465310/18322085/2d3eee30-7531-11e6-81bf-08a8e6afa3c5.png)

This might be a faulty sd card, but the text about reinstalling pibakery suggests it might be a pibakery issue?

**Comment by davidferguson** [comment]
That's an error that's passed straight through from resin-image-write, and I actually am not entirely sure what it means. Are you on Windows or Mac, and have you tried writing again?

**Comment by mrosseel** [comment]
I'm on Mac and already tried 2x, are there any prerequisites regarding SD card formatting?

**Comment by davidferguson** [comment]
Not as far as I know - it's always just worked with any SD when I've tried it. Just to check, what's the size of your SD?

**Comment by mrosseel** [comment]
4Gb

**Comment by davidferguson** [comment]
That's the issue - PiBakery uses Raspbian Full, which needs an 8GB or larger SD. I'm currently implementing support for Raspbian Lite, which will mean that 4GB cards can be used.

**Comment by mrosseel** [comment]
That indeed explains a lot :). Looking forward to the lite addition. Would be good to check the SD card size before writing, to avoid tickets like these. Thanks for your help!

**Comment by davidferguson** [comment]
That's a good idea - I'll try and add it to the next version.

**Comment by andragabr** [comment]
16gb card host Ubuntu 16.04
SD Write Failed

Error: undefined: not able to write image undefined

Please try writing to the SD card again.

If this error persists, please reinstall PiBakery.
![bake](https://cloud.githubusercontent.com/assets/2964968/23312636/1f587e04-fac3-11e6-8948-79e64e3c306c.png)

**Comment by davidferguson** [comment]
@andragabr There's an issue with my documentation - you'll need to have `kpartx` installed in order to use PiBakery on Linux.

On Debian and Ubuntu you can use `sudo apt-get install kpartx` to install it - once you've done that PiBakery should work fine.

**Comment by andragabr** [comment]
@davidferguson thanks a lot, Write Successful. I would love to help you with the documentation and get involved. I just started to learn raspberry pi and I am so enthusiast :)
